### PR TITLE
Bugfix done cards + Trelloscrum pattern without effort indication

### PR DESCRIPTION
**Pull request by juristr**
Hi,

**fix 1:**
for some reason cards within the "finished list" haven't been recognized any more. I'm not exactly sure what caused the issue, seems like it was a refactoring in the `helper.js`. Anyway, the problem was that the cards from the finished list have not been retrieved and thus weren't taken into account when creating the statistics.

**fix 2:**
I noticed that your implementation of the trelloscrum pattern did not allow to have something like this `(3) Card title`. This is basically the case when the user doesn't specify any effort yet, tipically during the planning where I wouldn't like to manually add a zero effort like `[0]..` to any card. Thus I tried to adapt the regex to also account for this scenario.
_(Note that I don't really like my implementation, it's kind of the opposite of an elegant implementation, but I needed it very urgently and my programming fu isn't the best - being sunday evening ;). So I may come back and refactor this unless you have a better fix already at hand.)_

### CODE REVIEW

**Comment by juristr** [comment]
Oh sorry...seems like for some reason I missed your fix (forgot a pull) which already corrected my **fix 2**. So ignore that one :)

**Comment by devtyr** [comment]
Is there something within your pull request to be merged?

**Comment by juristr** [comment]
Yep, it is this line:
https://github.com/juristr/trello-burndown/commit/858cea37094f29620761e798a5f9f24c6334cabb

for some reason, without this one it doesn't fetch the finished items. Although I can't really explain why this stopped working...

**Comment by devtyr** [comment]
I'll habe a look in it.

**Comment by devtyr** [comment]
@juristr I've added your mentioned line. Thanks for your work!

**Pull request closed without merging**
